export const CONTACT_OPEN_MODAL = "CONTACT_OPEN_MODAL";
export const CONTACT_CLOSE_MODAL = "CONTACT_CLOSE_MODAL";
export const IMG_OPEN_MODAL = "IMG_OPEN_MODAL";
export const IMG_CLOSE_MODAL = "IMG_CLOSE_MODAL";
export const SELECT_PYEONG = "SELECT_PYEONG";
